language: python
python:
 - "3.7-dev"
 - "nightly"
install:
 - pip install -r requirements.txt
 - pip install travis-sphinx
script:
 - python -m nose --with-doctest bushel
 - travis-sphinx build --source=docs/
after_success:
 - "[ \"$TRAVIS_PYTHON_VERSION\" = \"3.7-dev\" ] && travis-sphinx deploy"
