language: python
python:
 - "3.7-dev"
 - "nightly"
before_install:
 - sudo apt install graphviz
install:
 - pip install -r requirements.txt
 - pip install travis-sphinx
script:
 - python -m mypy --ignore-missing-imports bushel nagios/*
 - python -m nose --with-doctest bushel
 - travis-sphinx build --source=docs/
after_success:
 - "[ \"$TRAVIS_PULL_REQUEST\" = \"false\" ] && [ \"$TRAVIS_PYTHON_VERSION\" = \"3.7-dev\" ] && travis-sphinx deploy"
